/**
 * Coins and hearts. Client-side for now (localStorage); the spec moves this behind an
 * append-only server ledger in Phase 3, so everything here is a pure function of a wallet.
 */
export const MAX_HEARTS = 5
export const HEART_MS = 30 * 60 * 1000
export const EXTRA_MOVES = 5
export const EXTRA_MOVES_COST = 50

export interface Wallet {
  coins: number
  hearts: number
  /** When the next heart arrives, or null while hearts are full. */
  regenAt: number | null
}

export const newWallet = (): Wallet => ({ coins: 0, hearts: MAX_HEARTS, regenAt: null })

/** Credit any hearts that have regenerated by `now`. Returns the same object if nothing changed. */
export function tick(w: Wallet, now: number): Wallet {
  if (w.hearts >= MAX_HEARTS) return w.regenAt === null ? w : { ...w, regenAt: null }
  if (w.regenAt === null) return { ...w, regenAt: now + HEART_MS }
  let hearts = w.hearts
  let regenAt: number | null = w.regenAt
  while (hearts < MAX_HEARTS && regenAt !== null && now >= regenAt) {
    hearts++
    regenAt += HEART_MS
  }
  if (hearts >= MAX_HEARTS) regenAt = null
  return hearts === w.hearts && regenAt === w.regenAt ? w : { ...w, hearts, regenAt }
}

export function loseHeart(w: Wallet, now: number): Wallet {
  const t = tick(w, now)
  if (t.hearts <= 0) return t
  return { ...t, hearts: t.hearts - 1, regenAt: t.regenAt ?? now + HEART_MS }
}

export function refundHeart(w: Wallet): Wallet {
  const hearts = Math.min(MAX_HEARTS, w.hearts + 1)
  return { ...w, hearts, regenAt: hearts >= MAX_HEARTS ? null : w.regenAt }
}

export const msToNextHeart = (w: Wallet, now: number) => (w.regenAt === null ? 0 : Math.max(0, w.regenAt - now))

/** Coins for clearing a level. Replays pay 40% so repeating an easy level is not a strategy. */
export function levelReward(stars: number, movesLeft: number, firstClear: boolean): number {
  const full = 20 + stars * 10 + movesLeft * 2
  return firstClear ? full : Math.floor(full * 0.4)
}

export function spend(w: Wallet, cost: number): Wallet | null {
  return w.coins >= cost ? { ...w, coins: w.coins - cost } : null
}

export const earn = (w: Wallet, amount: number): Wallet => ({ ...w, coins: w.coins + amount })

const KEY = 'bentopia.wallet'

export function loadWallet(): Wallet {
  try {
    const raw = JSON.parse(localStorage.getItem(KEY) ?? 'null')
    if (raw && typeof raw.coins === 'number' && typeof raw.hearts === 'number') {
      return { coins: Math.max(0, raw.coins), hearts: Math.min(MAX_HEARTS, Math.max(0, raw.hearts)), regenAt: raw.regenAt ?? null }
    }
  } catch {
    /* storage unavailable or corrupt */
  }
  return newWallet()
}

export function saveWallet(w: Wallet) {
  try {
    localStorage.setItem(KEY, JSON.stringify(w))
  } catch {
    /* storage unavailable */
  }
}

export function formatCountdown(ms: number): string {
  const total = Math.ceil(ms / 1000)
  const m = Math.floor(total / 60)
  const s = total % 60
  return `${m}:${String(s).padStart(2, '0')}`
}
